config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :posts
  get 'posts/new'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end

     def new
     end

     def show
        @post = Post.find(params[:id])
     end

     def create
        @post = Post.new(post_params)
        @post.save
        redirect_to @post
     end

    

    private
     def post_params
        params.require(:post).permit(:title, :text)
     end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogTribehired</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>List of all Posts</h1>
<table>
<tr>
<th>Title</th>
<th>Body</th>
<tr>
<% @posts.each do |post| %>
</tr>
    <td>
        <%= post.title %>
    </td>
    <td>
        <%= truncate(post.text, length: 75) %>
    </td>
    <td>
    <%= link_to "Show", post_path(post) %>
    </td>
</td>
</tr>
<% end %>
<table>
<p>
    <%= link_to 'Home', welcome_index_path %>
</p>

app/views/posts/new.html.erb
<h1>Create a New Post!</h1>

<%= form_for :post, url:posts_path do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :text%>
    <%= f.text_area :text %>
<p>

<p>
    <%= f.submit%>
</p>

<% end %>

app/views/posts/show.html.erb
<p><strong>Title:<strong>
<%= @post.title %>
</p>

<p>
    <strong>
        Text:    
    </strong>
    <%= @post.text %>
</p>
<p><%= link_to 'Back', posts_path %> |
    <%= link_to 'Home', welcome_index_path %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome to the blog</h1>
<p><%= link_to 'My Blog', posts_path %></p>